# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.


entries:
- title: Sidebar
  product: Ramp Up Program
  version:
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage/
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage/
      output: pdf
      type: frontmatter

  - title: Ramp Up Home
    output: web, pdf
    folderitems:
    - title: Ramp Up Home
      url: /rampup_landing_page/
      output: web

  - title: PE Installation
    output: web, pdf
    folderitems:
    - title: Considerations
      url: /pe_installation/considerations/
      output: web

  - title: Choosing a Git Server
    output: web, pdf
    folderitems:
    - title: Considerations
      url: /git_server/considerations/
      output: web, pdf
    - title: GitLab
      url: /git_server/gitlab/
      output: web, pdf
    - title: Bitbucket
      url: /git_server/bitbucket/
      output: web, pdf
    - title: Github
      url: /git_server/github/
      output: web, pdf

  - title: Manage NTP
    output: web, pdf
    folderitems:
    - title: Manage NTP
      url: /manage_ntp/manage_ntp
      output: web, pdf
